### ISSUE TITLE
hi! can you help me set up the fonts on sketchybar?

### ISSUE THREAD

**Issue by mwufi** [Tnixc/dots#1]
currently mine looks like this
<img width="731" alt="image" src="https://user-images.githubusercontent.com/30219253/181416248-da20387a-7b75-459d-81e9-2424ccc33e0d.png">

I just did the things mentioned here
https://felixkratz.github.io/SketchyBar/setup#fonts

**Comment by enocla** [comment]
Sorry for being so late. Could I see your sketchybarrc?

**Comment by Shamiaza** [comment]
Hi, i've got the same problem atm, did you found a way to fix this up ? Love this bar btw

**Comment by enocla** [comment]
> Hi, i've got the same problem atm, did you found a way to fix this up ? Love this bar btw

Could I see your sketchybarrc? You might not have FiraCode Nerd Font installed.

**Comment by Shamiaza** [comment]
Hey thanks for the quick answer, i fixed it btw, it was as you were saying , my system couldn't recognize the font, i had to install it with brew rather then using the manual installers

**Comment by FormalSnake** [comment]
> https://felixkratz.github.io/SketchyBar/setup#fonts

can you give me the command please
