### ISSUE TITLE
How did you set up your firefox? And how do you hide most of your menu bar icons?

### ISSUE THREAD

**Issue by FormalSnake** [Tnixc/dots#3]
^^

**Comment by enocla** [comment]
Get started with firefox here: https://github.com/ranmaru22/firefox-vertical-tabs

and also https://apps.apple.com/us/app/hidden-bar/id1452453066?mt=12

**Comment by FormalSnake** [comment]
Thanks!

**Comment by FormalSnake** [comment]
> Get started with firefox here: https://github.com/ranmaru22/firefox-vertical-tabs
> 
> and also https://apps.apple.com/us/app/hidden-bar/id1452453066?mt=12

I also have the same issue as the other guy with the sketchybar fonts, but i cant find the correct command

**Comment by enocla** [comment]
What do you mean by correct command? For what?

**Comment by FormalSnake** [comment]
> What do you mean by correct command? For what?

My sketchybar has a block with a question mark in it, like another issue on this repository, I can't find the correct font, and the guy in the other issue solved it by downloading it via brew, but i can't find the correct command for it.

**Comment by FormalSnake** [comment]
<img width="1440" alt="Screenshot 2022-09-24 at 11 49 49" src="https://user-images.githubusercontent.com/90651091/192093899-52a7a6a2-a87c-48b7-8934-8028c8721135.png">

**Comment by FormalSnake** [comment]
or maybe the exact TFF file

**Comment by enocla** [comment]
> or maybe the exact TFF file

https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode

99.99% sure I used this

**Comment by FormalSnake** [comment]
did you use bold light normal or retina?

**Comment by FormalSnake** [comment]
> > or maybe the exact TFF file
> 
> https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode
> 
> 99.99% sure I used this

I managed to get the font to work, there was something wrong in the configuration for some reason, but the icons don't work

**Comment by FormalSnake** [comment]
Can you help me @Tnixc ?

**Comment by enocla** [comment]
> Can you help me @Tnixc ?

Could you send a screenshot of your font book, sketchybarrc, and bar itself?

**Comment by FormalSnake** [comment]
> > Can you help me @Tnixc ?
> 
> Could you send a screenshot of your font book, sketchybarrc, and bar itself?

I have decided to stop using it, it wasn't really practical
