### ISSUE TITLE
Help in VSCode

### ISSUE THREAD

**Issue by zer0yu** [Tnixc/dots#4]
Hi！Your vscode layout and theme look great, can you tell me in detail how you set it up?

**Comment by enocla** [comment]
https://marketplace.visualstudio.com/items?itemName=iocave.customize-ui

**Comment by zer0yu** [comment]
thx

**Comment by zer0yu** [comment]
Hello, I couldn't find a more beautiful setting.json than your vscode configuration. Can you make your setting.json public so I can learn from it?

**Comment by enocla** [comment]
Keep in mind the customizeUI extension has been broken since vscode 1.74.

Also uploaded the file.
