### ISSUE TITLE
Sketchybar icons not showing

### ISSUE THREAD

**Issue by Brutalino** [Tnixc/dots#5]
First of all... Great work. The dots are verry clear and the theme is amazing. I'm having problems with the setup of the sketchybar. The icons don't show up. I installed all the necessary fonts and it still doesn't work. Even in Vscode they don't show up
<img width="1428" alt="Screenshot 2023-03-07 alle 11 36 10" src="https://user-images.githubusercontent.com/100695292/223398382-d70fab4b-ee3d-4ba5-b367-be4aef53312c.png">

what should I do?

**Comment by enocla** [comment]
Are you sure it's Fira Code Nerd Font Mono? Check the font name in font book to see it. Also run chomd +x * in the dir to allow all the scripts to work.

**Comment by Brutalino** [comment]
> Are you sure it's Fira Code Nerd Font Mono? Check the font name in font book to see it. Also run chomd +x * in the dir to allow all the scripts to work.

I installed the wrong fira code font. It works now. The only things missing are the plugins. I don't know why they dont work.

**Comment by enocla** [comment]
Chmod +x * or chomd 777 the sh files.

**Comment by Brutalino** [comment]
> Chmod +x * or chomd 777 the sh files.

Thanks. Everything works now
