### ISSUE TITLE
Vs code tabs

### ISSUE THREAD

**Issue by NorbertBodziony** [Tnixc/dots#7]
Hey,
Really love setup. Vs code tabs caught my eye. I couldn't figure out how to do it. Do you mind giving me a hint ?
<img width="370" alt="image" src="https://user-images.githubusercontent.com/38857779/234412730-8e3ff511-5c14-48bc-b5f5-87d8b06773bb.png">

**Comment by enocla** [comment]
It's not possible anymore since the extension broke

**Comment by enocla** [comment]
It is now
